name: "Build & Deploy CMS to Staging"

on:
  push:
    branches: [main]
    paths:
      - cms/**
      - .github/workflows/cms-deploy-staging.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  test:
    uses: ./.github/workflows/cms-unit-tests.yml

  release:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: cms/.node-version
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: cms/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: cms

      - name: Build
        run: npm run build
        working-directory: cms
